---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.4.1
  network:
    - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: ubuntu-16.04
  run_list:
    - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  attributes:
    yum:
      epel:
        mirrorlist: http://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
        gpgkey: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
        sslverify: false
- name: centos-7.2

suites:
- name: default
  run_list:
    - 'recipe[kibana]'
  attributes:
    kibana:
      version: '4.6.3'
- name: tarball_default
  run_list:
    - 'recipe[kibana]'
  attributes:
    kibana:
      version: '4.6.3'
      install_method: 'tarball'
      service:
        bin_path: 'kibana/bin'
- name: kibana4_apache
  run_list:
    - 'recipe[netstat]'
    - 'recipe[apache2]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
    - 'recipe[kibana]'
    - 'recipe[kibana::apache]'
  attributes:
    apache:
      listen:
       - '*:8080'
    kibana:
      version: '4'
      apache:
        port: 8080
      interface: '0.0.0.0'
    java:
      jdk_version: '8'
- name: kibana4_nginx
  run_list:
    - 'recipe[netstat]'
    - 'recipe[chef_nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
    - 'recipe[kibana]'
    - 'recipe[kibana::nginx]'
  attributes:
    kibana:
      version: '4'
      interface: '0.0.0.0'
      nginx:
        listen_http: 8080
    java:
      jdk_version: '8'
- name: kibana4_apache_package
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes:
    apache:
      listen:
       - '*:8080'
    kibana:
      install_method: 'package'
      version: '4'
      apache:
        port: 8080
      interface: '0.0.0.0'
      service:
        options: '--max-old-space-size=100'
- name: kibana4_nginx_package
  run_list:
    - 'recipe[netstat]'
    - 'recipe[chef_nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
    - 'recipe[kibana]'
    - 'recipe[kibana::nginx]'
  attributes:
    kibana:
      install_method: 'package'
      version: '4'
      interface: '0.0.0.0'
      nginx:
        listen_http: 8080
    java:
      jdk_version: '8'
