---
driver:
  name: docker
  privileged: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    driver_config:
      run_command: /sbin/init
  - name: centos-6.9
  - name: centos-7.4.1708
    driver_config:
      image: centos:7
      provision_command: yum -y install initscripts
      run_command: /usr/sbin/init
