---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.4.1
  network:
    - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  attributes:
    yum:
      epel:
        mirrorlist: http://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
        gpgkey: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6
        sslverify: false

suites:
- name: kibana3_apache
  run_list:
    - 'recipe[netstat]'
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes: {}
- name: kibana3_nginx
  run_list:
    - 'recipe[netstat]'
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
  attributes: {}
- name: kibana3_source
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes:
    kibana:
      install_method: 'source'
- name: kibana4
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    apache:
      listen_ports:
       - 8080
    kibana:
      version: '4'
      apache:
        port: 8080
      interface: '0.0.0.0'
- name: kibana4_nginx
  run_list:
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    kibana:
      version: '4'
      interface: '0.0.0.0'
      nginx:
        listen_http: 8080
