---
driver:
  name: dokken
  privileged: true

platforms:
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
    run_list:
      - recipe[apt]
  # - name: centos-6.9
  # - name: centos-7.4.1708
  #   driver_config:
  #     image: centos:7
  #     provision_command: yum -y install initscripts
  #     run_command: /usr/sbin/init
