---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
    - recipe[apt]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: kibana3_apache
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes: {}
- name: kibana3_nginx
  run_list:
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
  attributes: {}
- name: kibana3_source
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
  attributes:
    kibana:
      install_method: 'source'
- name: kibana4
  run_list:
    - 'recipe[kibana]'
    - 'recipe[apache2]'
    - 'recipe[kibana::apache]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    apache:
      listen_ports:
       - 8080
    kibana:
      version: '4'
      apache:
        port: 8080
- name: kibana4_nginx
  run_list:
    - 'recipe[kibana]'
    - 'recipe[nginx]'
    - 'recipe[kibana::nginx]'
    - 'recipe[java]'
    - 'recipe[elasticsearch]'
  attributes:
    kibana:
      version: '4'
      nginx:
        listen_http: 8080
